server:
  port: 8088
spring:
  profiles:
    active: prod
  cloud:
    config:
      server:
        git:
          uri: https://github.com/HwttwH/cloud-config-test
          username: 2415949506@qq.com
          password: 123456789zy0
          default-label: master
